version: '3.8'

services:
  backend:
    build: ./backend
    container_name: exam-api
    ports:
      - "3000:3000"
    networks:
      - exam-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: exam-frontend-dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - exam-network

networks:
  exam-network:
    driver: bridge